kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: ebpf-exporter-priv
subjects:
  - kind: ServiceAccount
    name: ebpf-exporter-robot
    namespace: ebpf-exporter
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: 'system:openshift:scc:privileged'
