apiVersion: v1
kind: Service
metadata:
  name: ebpf-exporter
  namespace: ebpf-exporter
spec:
  selector:
    app: ebpf-exporter
  ports:
    - name: metrics
      protocol: TCP
      port: 9435
      targetPort: metrics
