apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: ebpf-exporter
  namespace: openshift-monitoring
spec:
  endpoints:
    - interval: 30s
      path: /metrics
      port: metrics
      scheme: http
  namespaceSelector:
    matchNames:
      - ebpf-exporter
  selector: {}
