kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: cluster-monitoring-operator
  namespace: ebpf-exporter
subjects:
  - kind: ServiceAccount
    name: cluster-monitoring-operator
    namespace: openshift-monitoring
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-monitoring-operator-namespaced
